
BIN = test-hp203b

OBJECTS = $(patsubst %.c,%.o,$(wildcard *.c))

CFLAGS += -Wall \
	-Werror \
	-O3 \
	-I/opt/vc/include

LDFLAGS +=

all: $(BIN)

$(BIN): $(OBJECTS)
	gcc $(OBJECTS) $(LDFLAGS) -o $@

%.o: %.c
	gcc $(CFLAGS) -c $< -o $@
